export enum MessageType {
  SYSTEM = 'SYSTEM',
  ACTIVITY_SUBMITTED = 'ACTIVITY_SUBMITTED',
  ACTIVITY_APPROVED = 'ACTIVITY_APPROVED',
  ACTIVITY_REJECTED = 'ACTIVITY_REJECTED',
  ACTIVITY_JOIN = 'ACTIVITY_JOIN',
}

export enum MessageRelatedType {
  ACTIVITY = 'ACTIVITY',
  SYSTEM = 'SYSTEM',
}
