export enum MessageType {
  SYSTEM = 'SYSTEM',
  ACTIVITY_SUBMITTED = 'ACTIVITY_SUBMITTED',
  ACTIVITY_APPROVED = 'ACTIVITY_APPROVED',
  ACTIVITY_REJECTED = 'ACTIVITY_REJECTED',
  ACTIVITY_JOIN = 'ACTIVITY_JOIN',
  POST_SUBMITTED = 'POST_SUBMITTED',
  POST_APPROVED = 'POST_APPROVED',
  POST_REJECTED = 'POST_REJECTED',
  AFTER_SALES_SUBMITTED = 'AFTER_SALES_SUBMITTED',
  AFTER_SALES_APPROVED = 'AFTER_SALES_APPROVED',
  AFTER_SALES_REJECTED = 'AFTER_SALES_REJECTED',
  AFTER_SALES_PENDING_ADMIN = 'AFTER_SALES_PENDING_ADMIN',
}

export enum MessageRelatedType {
  ACTIVITY = 'ACTIVITY',
  POST = 'POST',
  SYSTEM = 'SYSTEM',
  ORDER = 'ORDER',
}
