package com.lfc.consumer.analytics

object AnalyticsEvents {
    const val APP_OPEN = "app_open"
    const val SCREEN_VIEW = "screen_view"
    const val FEED_TAB_SWITCH = "feed_tab_switch"
    const val FEED_CHANNEL_SWITCH = "feed_channel_switch"
    const val FEED_REFRESH = "feed_refresh"
    const val ACTIVITY_FEED_REFRESH = "activity_feed_refresh"
    const val FEED_LOAD_MORE = "feed_load_more"
    const val CONTENT_CLICK = "content_click"
    const val POST_VIEW = "post_view"
    const val POST_CREATE = "post_create"
    const val POST_UPDATE = "post_update"
    const val POST_LIKE = "post_like"
    const val POST_FAVORITE = "post_favorite"
    const val POST_COMMENT = "post_comment"
    const val COMMENT_LIKE = "comment_like"
    const val PRODUCT_VIEW = "product_view"
    const val PRODUCT_PURCHASE_START = "product_purchase_start"
    const val ACTIVITY_VIEW = "activity_view"
    const val ACTIVITY_CREATE = "activity_create"
    const val ACTIVITY_JOIN = "activity_join"
    const val ACTIVITY_LIKE = "activity_like"
    const val ACTIVITY_FAVORITE = "activity_favorite"
    const val SEARCH_SUBMIT = "search_submit"
    const val SEARCH_TAB_SWITCH = "search_tab_switch"
    const val PROFILE_VIEW = "profile_view"
    const val USER_FOLLOW = "user_follow"
    const val CHAT_SEND = "chat_send"
    const val CHAT_OPEN = "chat_open"
    const val NOTIFICATION_OPEN = "notification_open"
    const val PAYMENT_START = "payment_start"
    const val PAYMENT_SUCCESS = "payment_success"
    const val PROMOTION_PAY = "promotion_pay"
    const val MESSAGE_TAB = "message_tab_open"
    const val USER_LOGIN = "user_login"
    const val USER_REGISTER = "user_register"
}
