import Foundation

enum AnalyticsEvents {
  static let appOpen = "app_open"
  static let screenView = "screen_view"
  static let feedTabSwitch = "feed_tab_switch"
  static let feedChannelSwitch = "feed_channel_switch"
  static let feedRefresh = "feed_refresh"
  static let activityFeedRefresh = "activity_feed_refresh"
  static let feedLoadMore = "feed_load_more"
  static let contentClick = "content_click"
  static let postView = "post_view"
  static let postCreate = "post_create"
  static let postUpdate = "post_update"
  static let postLike = "post_like"
  static let postFavorite = "post_favorite"
  static let postComment = "post_comment"
  static let commentLike = "comment_like"
  static let productView = "product_view"
  static let productPurchaseStart = "product_purchase_start"
  static let activityView = "activity_view"
  static let activityCreate = "activity_create"
  static let activityJoin = "activity_join"
  static let activityLike = "activity_like"
  static let activityFavorite = "activity_favorite"
  static let searchSubmit = "search_submit"
  static let searchTabSwitch = "search_tab_switch"
  static let profileView = "profile_view"
  static let userFollow = "user_follow"
  static let chatSend = "chat_send"
  static let chatOpen = "chat_open"
  static let notificationOpen = "notification_open"
  static let paymentStart = "payment_start"
  static let paymentSuccess = "payment_success"
  static let promotionPay = "promotion_pay"
  static let messageTab = "message_tab_open"
  static let userLogin = "user_login"
  static let userRegister = "user_register"
}
